import * as ATTRIBUTES from "./attributes.mjs";
import * as GLOBAL_SECONDARY_INDEXES from "./globalSecondaryIndexes.mjs";

// TABLE //
const TABLE = {
  NAME: "PlacesTableFr",
  HASH_KEY: ATTRIBUTES.SLUG,
  RANGE_KEY: ATTRIBUTES.COUNTY,
};

// ATTRIBUTES //
const ATTRIBUTES_DEFINITION = new Map();

ATTRIBUTES_DEFINITION.set(ATTRIBUTES.SLUG, {
  name: ATTRIBUTES.SLUG,
  type: "S",
});
ATTRIBUTES_DEFINITION.set(ATTRIBUTES.COUNTY, {
  name: ATTRIBUTES.SLUG,
  type: "S",
});
ATTRIBUTES_DEFINITION.set(ATTRIBUTES.TYPE, {
  name: ATTRIBUTES.SLUG,
  type: "S",
});
ATTRIBUTES_DEFINITION.set(ATTRIBUTES.GEOHASH, {
  name: ATTRIBUTES.SLUG,
  type: "S",
});
ATTRIBUTES_DEFINITION.set(ATTRIBUTES.CODE, {
  name: ATTRIBUTES.SLUG,
  type: "S",
});
ATTRIBUTES_DEFINITION.set(ATTRIBUTES.POPULATION, {
  name: ATTRIBUTES.SLUG,
  type: "N",
});

// GLOBAL SECONDARY INDEXES //
const GLOBAL_SECONDARY_INDEXES_DEFINITION = new Map();

GLOBAL_SECONDARY_INDEXES_DEFINITION.set(
  GLOBAL_SECONDARY_INDEXES.CountyTypeGSI,
  {
    name: GLOBAL_SECONDARY_INDEXES.CountyTypeGSI,
    hashKey: ATTRIBUTES.COUNTY,
    rangeKey: ATTRIBUTES.TYPE,
  }
);
GLOBAL_SECONDARY_INDEXES_DEFINITION.set(
  GLOBAL_SECONDARY_INDEXES.GeohashTypeGSI,
  {
    name: GLOBAL_SECONDARY_INDEXES.GeohashTypeGSI,
    hashKey: ATTRIBUTES.GEOHASH,
    rangeKey: ATTRIBUTES.TYPE,
  }
);
GLOBAL_SECONDARY_INDEXES_DEFINITION.set(GLOBAL_SECONDARY_INDEXES.CodeTypeGSI, {
  name: GLOBAL_SECONDARY_INDEXES.CodeTypeGSI,
  hashKey: ATTRIBUTES.CODE,
  rangeKey: ATTRIBUTES.TYPE,
});
GLOBAL_SECONDARY_INDEXES_DEFINITION.set(
  GLOBAL_SECONDARY_INDEXES.TypePopulationGSI,
  {
    name: GLOBAL_SECONDARY_INDEXES.TypePopulationGSI,
    hashKey: ATTRIBUTES.TYPE,
    rangeKey: ATTRIBUTES.POPULATION,
  }
);

export default {
  TABLE,
  GLOBAL_SECONDARY_INDEXES_DEFINITION,
  ATTRIBUTES_DEFINITION,
};
